auth:
  hub.docker.com:
    username: $USERNAME
    password: $PASSWORD
images:
  k8s.gcr.io/metrics-server/metrics-server: fansir2022/metrics-server
  k8s.gcr.io/ingress-nginx/controller: fansir2022/ingress-nginx-controller
  k8s.gcr.io/git-sync/git-sync: fansir2022/git-sync
  gcr.io/kaniko-project/executor:debug,latest: fansir2022/kaniko-executor
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: fansir2022/kube-state-metrics
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: fansir2022/nfs-subdir-external-provisioner
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: fansir2022/prometheus-adapter
